config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users
  root 'events#index'
  get 'user_custom/update'
  get 'pages/dashboard'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :category
  belongs_to :user, :foreign_key => :user_parent_id
  extend SimpleCalendar
  has_calendar :attribute => :datetime

  has_attached_file :image,
          :styles => { :original => "1920x500#",
                       :thumb => "1000x250#"},
          :convert_options => { :thumb => '-blur 0x16 -modulate 70,60' }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def set_user!(user)
    self.user_parent_id = user.id
    self.save!
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :events
  has_many :createdEvents, :foreign_key => 'user_parent_id', :class_name => "Event"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_format_of :email,
      with: /(.)*\@rit\.edu/, message: 'must be RIT student email.'

end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def is_op_or_admin?(event)
    if current_user.admin == true
      return true
    elsif event.user == current_user
      return true
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :secure

  # GET /events
  # GET /events.json
  def index
    if params[:filter] == nil
      @events = Event.where(["datetime >= ?", Date.today]).paginate(:page => params[:page], :per_page => 6).order("datetime ASC")
    elsif params[:filter] == 'onfloor'
      @events = Category.find(1).events.where(["datetime >= ?", Date.today]).paginate(:page => params[:page], :per_page => 30).order("datetime ASC")
    elsif params[:filter] == 'offfloor'
      @events = Category.find(2).events.where(["datetime >= ?", Date.today]).paginate(:page => params[:page], :per_page => 30).order("datetime ASC")
    elsif params[:filter] == 'all'
      @events = Event.all
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    if is_op_or_admin?(@event) == false
      redirect_to events_path
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.set_user!(current_user)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    if is_op_or_admin?(@event)
      respond_to do |format|
        if @event.update(event_params)
          format.html { redirect_to @event, notice: 'Event was successfully updated.' }
          format.json { render :show, status: :ok, location: @event }
        else
          format.html { render :edit }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    if is_op_or_admin?(@event)
      @event.destroy
      respond_to do |format|
        format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def secure
      redirect_to new_user_session_path unless user_signed_in?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :datetime, :category_id, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    @myEvents = User.find(current_user.id).createdEvents
    @events = User.find(current_user.id).events
    @eventsFuture = User.find(current_user.id).events.where(["datetime >= ?", Date.today]).order("datetime ASC")
    @eventsPast = User.find(current_user.id).events.where(["datetime < ?", Date.today]).order("datetime ASC")
  end
end

app/controllers/user_custom_controller.rb
class UserCustomController < ApplicationController
  def update
    @event = Event.find(params[:event])
    if User.find(current_user.id).events.find_by_id(@event.id) == nil && params[:signup] == 'yes'
      @event.users << User.find(current_user.id)
    elsif User.find(current_user.id).events.find_by_id(@event.id) != nil && params[:signup] == 'no'
      @event.users.delete(User.find(current_user.id))
    end
    redirect_to @event
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    if user_signed_in?
      if current_user.admin
        return true
      end
    end
  end

  def sign_up_button(event, *htmlclass)
    signedup = false
    event.users.each do |user|
      user.id == current_user.id ? signedup = true : nil
    end
    if user_signed_in?
      if signedup == false
        link_to "Sign Up for Event", "#{user_custom_update_path}?event=#{event.id}&signup=yes", class: "btn btn-default right #{htmlclass[0]}"
      else
        link_to "No Longer Attending", "#{user_custom_update_path}?event=#{event.id}&signup=no", class: "btn btn-danger right #{htmlclass[0]}"
      end
    end
  end

  def is_signed_up?(event)
    signedup = false
    event.users.each do |user|
      user.id == current_user.id ? signedup = true : nil
    end
    return signedup
  end

  def is_op_or_admin?(event)
    if current_user.admin == true
      return true
    elsif event.user == current_user
      return true
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper



end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_custom_helper.rb
module UserCustomHelper
end

app/views/events/_form.html.erb
<%= form_for @event, :html => {:class => "form-horizontal event", :multipart => true } do |f| %>

    <% if @event.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being
              saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @event.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'form-control' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :datetime, :class => 'control-label' %>
      <div class="controls">
        <%= f.datetime_select :datetime, :class => 'form-control' %>
      </div>
    </div>

        <%= f.file_field :image %>


    <div class="control-group">
      <%= f.label :category, :class => 'control-label' %>
      <div class="controls">
        <%= f.collection_select(:category_id, Category.all, :id, :name) %>
      </div>
    </div>


    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn btn-default' %>



<% end %>

app/views/events/_table.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:description) %></th>
    <th><%= model_class.human_attribute_name(:datetime) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @events.each do |event| %>
      <tr id='row-<%= event.id %>'>
        <td><%= link_to event.id, event_path(event) %></td>
        <td><%= event.name %></td>
        <td><%= event.datetime.strftime('%A, %b %d') %></td>
        <td><%=l event.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(@event),
                      :method => 'delete',
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= link_to 'Upcoming', "#{events_path}", class: "btn btn-default" %>
<%= link_to 'On Floor', "#{events_path}?filter=onfloor", class: "btn btn-default" %>
<%= link_to 'Off Floor', "#{events_path}?filter=offfloor", class: "btn btn-default" %>

<hr>

<div style="overflow: hidden">
  <% if @events != nil %>
      <% @events.each do |event| %>
          <%= link_to (event_path(event)) do %>
              <div class="line" style="background: url(<%= event.image.url(:thumb) %>)">
                <h2><%= event.name %></h2>
                <p class="description"></p>
                <div class='meta'>
                  <div class="col-md-4"><%= event.datetime.strftime('%A, %b %d, %Y') %></div>
                  <div class="col-md-6"><%= event.category.name.capitalize %></div>
                  <div class="col-md-2"><%= event.users.count %> Attending</div>
                </div>
              </div>
          <% end %>
      <% end %>
  <% else %>
    nothing found
  <% end %>
</div>

<%= will_paginate @posts %>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>

<div class="headerImage" style="background: url(<%= @event.image.url %>) no-repeat 0 0 fixed;" data-stellar-background-ratio="0.5">

</div>
<div class="card">

  <h1><%= @event.name.capitalize %></h1>

  <hr/>

  <p class="time">

    <%= @event.datetime.strftime('%A, %b %d, %Y') %> | <%= @event.users.count %> Currently Attending&nbsp;&nbsp;&nbsp;&nbsp;<%= sign_up_button(@event) %>
  </p>

  <p><%= @event.description %></p>

  <% if @event.user %>
    <p>Created by <%= @event.user.email %></p>
  <% end %>
  <% if @event.users.count > 0 %>
      <hr/>
      <% @event.users.each do |user| %>
          <p class="users"><%= user.email %></p>
      <% end %>
  <% end %>


  <hr/>


  <%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn btn-default' %>

  <% if is_op_or_admin?(@event) %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_event_path(@event), :class => 'btn btn-default' %><br/><br/>
      <%= button_to 'Delete', event_path(@event), :method => 'delete', :class => 'btn btn-danger' %>
  <% end %>

  <br/>
  <br/>
  <br/>
  <br/>
  <br/>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shiftyspace</title>
  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Playfair+Display:400,700,400italic|Roboto:400,300,100' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%#= current_user.email %>
<% if user_signed_in? %>
    <header>

      <%= link_to 'Shifty Space', root_path, class: 'title' %>
      <%= link_to current_user.email, pages_dashboard_path,
                  :class => 'btn btn-default' %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete,
                  :class => 'btn btn-default' %>
      <%= link_to t('.new', :default => t("helpers.links.new")),
                  new_event_path,
                  :class => 'btn btn-primary' %>
    </header>
<% end %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pages/dashboard.html.erb
<h3>My Upcoming Events</h3>
<hr>
<%= month_calendar table: {class: "calendar table table-bordered"}, events: @events do |date, event| %>
    <%= date %>

    <% event.each do |event| %>
        <div>
          <%= link_to event.name, event_path(event) %><br/>

          <div class="smalldate"><%= event.datetime.strftime('%I:%M%p') %></div>
        </div>
    <% end %>
<% end %>

<br/>
<br/>
<br/>

<% if @myEvents.count > 0 %>
    <h3>My Created Events</h3>
    <hr>
    <table style="width: 100%" class="table table-bordered">
      <thead>
      <tr>
        <th>
          Title
        </th>
        <th>
          Date and Time
        </th>
        <th>
          Users Signed Up
        </th>
        <th>
          Your Status
        </th>
      </tr>
      </thead>
      <% @myEvents.each do |event| %>
          <tr>
            <td>
              <%= link_to event.name, event_path(event) %>
            </td>
            <td>
              <%= event.datetime.strftime('%A, %b %d, %Y at %I:%M%p') %>
            </td>
            <td>
              <%= event.users.count %>
            </td>
            <td>
              <%= is_signed_up?(event) ? "Signed Up" : "Not Signed Up" %>
            </td>
          </tr>
      <% end %>
    </table>
<% end %>

   <br/>
   <br/>
   <br/>
   <br/>